version: '3.3'

services:
  sudoku:
    build: .
    container_name: lettuce-portfolio
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
networks:
  default:
    external:
      name: nginx
